events {
    worker_connections 1024;
}

http {
    upstream kong_cluster {
        server kong1:8000;
        server kong2:8000;
    }

    upstream kong_admin {
        server kong1:8001;
        server kong2:8001;
    }

    server {
        listen 8000;

        location / {
            proxy_pass http://kong_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    server {
        listen 8001;

        location / {
            proxy_pass http://kong_admin;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
